FROM node:22.14-alpine


WORKDIR /app

RUN apk add --no-cache bash

# Copiar archivos de configuración
COPY package*.json ./
COPY tsconfig*.json ./
COPY eslint.config.ts ./
COPY .eslintignore ./

# Instalar dependencias
RUN npm install --include=dev

# Copiar el resto del código
COPY . .

# Exponer puerto
EXPOSE 5173

# Comando por defecto
CMD ["npm", "run", "dev"]
