FROM node:22.14.0-alpine3.21 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
# Eliminar la siguiente línea si existe
# COPY .eslintignore ./
RUN npm run build

FROM nginx:1.27.3-alpine3.21
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
