name: sgc

services:
  frontend:
    container_name: sgc_frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: always
    networks:
      - sgc_network

  backend:
    container_name: sgc_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

      # Application settings
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: always
    networks:
      - sgc_network
    healthcheck:
      test: [ "CMD", "python", "-c", "from database import get_db_connection; get_db_connection()" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    container_name: sgc_db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"   # Expone el puerto para acceso externo (solo si es necesario)
    volumes:
      - sgc_db_data:/var/lib/mysql
      - ./database/00_init_database.sql:/docker-entrypoint-initdb.d/00_init_database.sql
      - ./database/01_structure.sql:/docker-entrypoint-initdb.d/01_structure.sql
      - ./database/02_initial_data.sql:/docker-entrypoint-initdb.d/02_initial_data.sql
      - ./database/03_procedures.sql:/docker-entrypoint-initdb.d/03_procedures.sql
    command: >-
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --default-authentication-plugin=mysql_native_password 
      --max-connections=500 
      --max_allowed_packet=128M
    networks:
      - sgc_network
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=${DB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sgc_network:
    name: sgc_network
    driver: bridge

volumes:
  sgc_db_data:
    driver: local
