
services:
  frontend:
    build:
      context: ./Client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./Client/.env
    restart: always

  backend:
    build:
      context: ./Server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./Server/.env
    volumes:
      - ./Server/database:/app/database
    restart: always

  db:
    image: mariadb:latest
    restart: always
    env_file:
      - ./Server/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
