version: '3.8'

services:
  frontend:
    build:
      context: ./Client
    ports:
      - "80:80"
    depends_on:
      - backend
      - db
    env_file:
      - ./Client/.env

  backend:
    build:
      context: ./Server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./Server/.env

  db:
    image: mariadb:latest
    restart: always
    env_file:
      - ./Server/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
