DELIMITER //

CREATE PROCEDURE GetAllTypeCourses()
BEGIN
    SELECT TYPES_COURSES.id, TYPES_COURSES.name 
    FROM TYPES_COURSES;
END//

DELIMITER ;

DELIMITER //

CREATE PROCEDURE InsertTypeCourse(
    IN course_name VARCHAR(255)
)
BEGIN
    INSERT INTO TYPES_COURSES (name) VALUES (course_name);
END//

DELIMITER ;


DELIMITER //

CREATE PROCEDURE DeleteTypeCourseById(
    IN course_id INT
)
BEGIN
    DELETE FROM TYPES_COURSES WHERE id = course_id;
END//

DELIMITER ;
