-- Script de inicialización de la base de datos
-- Desactiva las restricciones de clave foránea temporalmente
SET FOREIGN_KEY_CHECKS = 0;

-- Eliminación de tablas en orden inverso a sus dependencias
DROP TABLE IF EXISTS WORKSHOPS_GRADES;
DROP TABLE IF EXISTS WORKSHOPS_INSCRIPTIONS;
DROP TABLE IF EXISTS CONVALIDATIONS;
DROP TABLE IF EXISTS REQUESTS;
DROP TABLE IF EXISTS SUBJECTS;
DROP TABLE IF EXISTS CURRICULUM_COURSES;
DROP TABLE IF EXISTS WORKSHOPS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS ADMINISTRATORS;
DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS TYPES_CURRICULUM_COURSES;
DROP TABLE IF EXISTS TYPES_CONVALIDATIONS;

-- Reactiva las restricciones de clave foránea
SET FOREIGN_KEY_CHECKS = 1;