FROM python:3.11.11-slim-bookworm

WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    FROM python:3.11.11-slim-bookworm

    WORKDIR /app

    RUN apt-get update && apt-get install -y \
        gcc \
        default-libmysqlclient-dev \
        pkg-config \
        && rm -rf /var/lib/apt/lists/*

    COPY requirements.txt .
    COPY requirements-dev.txt .

    RUN pip install --no-cache-dir -r requirements.txt
    RUN pip install --no-cache-dir -r requirements-dev.txt

    COPY . .

    RUN mkdir -p /app/files/convalidations/personal_projects && \
        mkdir -p /app/files/convalidations/certificated_courses && \
        mkdir -p /app/files/workshops/syllabus && \
        mkdir -p /app/files/workshops/convalidation_list

    EXPOSE 8000

    CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
