export const env = {
    API_URL: import.meta.env.VITE_API_URL,
  
    REQUESTS_ENDPOINT: import.meta.env.VITE_REQUESTS_ENDPOINT,
    REQUESTS_ID_ENDPOINT: import.meta.env.VITE_REQUESTS_ID_ENDPOINT,
    REQUESTS_ROL_ENDPOINT: import.meta.env.VITE_REQUESTS_ROL_ENDPOINT,
    REQUESTS_DATE_ENDPOINT: import.meta.env.VITE_REQUESTS_DATE_ENDPOINT,
    REQUESTS_FILTERED_ENDPOINT: import.meta.env.VITE_REQUESTS_FILTERED_ENDPOINT,
    REQUESTS_STATE_ENDPOINT: import.meta.env.VITE_REQUESTS_STATE_ENDPOINT,
  
    CURRICULM_COURSES_ENDPOINT: import.meta.env.VITE_CURRICULM_COURSES_ENDPOINT,
  
    SUBJECTS_ENDPOINT: import.meta.env.VITE_SUBJECTS_ENDPOINT,
    SUBJECTS_ID_ENDPOINT: import.meta.env.VITE_SUBJECTS_ID_ENDPOINT,
  
    TYPES_CONVALIDATION_ENDPOINT: import.meta.env.VITE_TYPES_CONVALIDATION_ENDPOINT,
    TYPES_CURRICULM_COURSES: import.meta.env.VITE_TYPES_CURRICULM_COURSES,
  
    WORKSHOPS_ENDPOINT: import.meta.env.VITE_WORKSHOPS_ENDPOINT,
    WORKSHOPS_AVAILABLE_ENDPOINT: import.meta.env.VITE_WORKSHOPS_AVAILABLE_ENDPOINT,
    WORKSHOPS_AVAILABLE_ID_ENDPOINT: import.meta.env.VITE_WORKSHOPS_AVAILABLE_ID_ENDPOINT,
    WORKSHOPS_AVAILABLE_STUDENT_ENDPOINT: import.meta.env.VITE_WORKSHOPS_AVAILABLE_STUDENT_ENDPOINT,
    WORKSHOPS_COMPLETED_STUDENT_ENDPOINT: import.meta.env.VITE_WORKSHOPS_COMPLETED_STUDENT_ENDPOINT,
    WORKSHOPS_AVAILABLE_ENROLLED_STUDENT_ENDPOINT: import.meta.env.VITE_WORKSHOPS_AVAILABLE_ENROLLED_STUDENT_ENDPOINT,
    WORKSHOPS_SEMESTER_ENDPOINT: import.meta.env.VITE_WORKSHOPS_SEMESTER_ENDPOINT,
  
    WORKSHOP_INSCRIPTIONS_ENDPOINT: import.meta.env.VITE_WORKSHOP_INSCRIPTIONS_ENDPOINT,
    WORKSHOP_INSCRIPTIONS_STUDENT_ENDPOINT: import.meta.env.VITE_WORKSHOP_INSCRIPTIONS_STUDENT_ENDPOINT,
  
    DEPARTMENTS_ENDPOINT: import.meta.env.VITE_DEPARTMENTS_ENDPOINT,
    DEPARTMENTS_ID_ENDPOINT: import.meta.env.VITE_DEPARTMENTS_ID_ENDPOINT,
  };
  