"""
Constantes de nombres de tablas de la base de datos
Sistema: SGSCT

Centraliza todos los nombres de tablas para evitar hardcoding
y facilitar mantenimiento.
"""


class Tables:
    """Nombres de tablas de la base de datos"""
    
    # AUTH
    AUTH_USERS = "AUTH_USERS"
    USERS = "USERS"
    
    # CATALOG
    CAMPUS = "CAMPUS"
    USER_TYPES = "USER_TYPES"
    CONVALIDATION_TYPES = "CONVALIDATION_TYPES"
    CONVALIDATION_STATES = "CONVALIDATION_STATES"
    WORKSHOP_STATES = "WORKSHOP_STATES"
    CURRICULUM_COURSES_TYPES = "CURRICULUM_COURSES_TYPES"
    
    # ACADEMIC
    DEPARTMENTS = "DEPARTMENTS"
    SUBJECTS = "SUBJECTS"
    CURRICULUM_COURSE_SLOTS = "CURRICULUM_COURSE_SLOTS"
    
    # USERS
    PROFESSORS = "PROFESSORS"
    
    # WORKSHOPS
    WORKSHOPS = "WORKSHOPS"
    WORKSHOPS_TOKENS = "WORKSHOPS_TOKENS"
    WORKSHOPS_INSCRIPTIONS = "WORKSHOPS_INSCRIPTIONS"
    WORKSHOPS_GRADES = "WORKSHOPS_GRADES"
    
    # CONVALIDATIONS
    CONVALIDATIONS = "CONVALIDATIONS"
    CONVALIDATIONS_SUBJECTS = "CONVALIDATIONS_SUBJECTS"
    CONVALIDATIONS_WORKSHOPS = "CONVALIDATIONS_WORKSHOPS"
    CONVALIDATIONS_EXTERNAL_ACTIVITIES = "CONVALIDATIONS_EXTERNAL_ACTIVITIES"
    REQUESTS = "REQUESTS"
