#TYPES_CONVALIDATIONS

DROP PROCEDURE IF EXISTS GetAllTypesConvalidations;

#TYPES_CURRICULUM_COURSES

DROP PROCEDURE IF EXISTS GetAllTypesCurriculumCourses;

#DEPARTMENT

DROP PROCEDURE IF EXISTS GetAllDepartments;

DROP PROCEDURE IF EXISTS InsertDepartment;

DROP PROCEDURE IF EXISTS UpdateDepartmentByID;

#CURRICULUM_COURSES

DROP PROCEDURE IF EXISTS GetAllCurriculumCourses;

DROP PROCEDURE IF EXISTS InsertCurriculumCourse;

DROP PROCEDURE IF EXISTS UpdateCurriculumCourseByID;

#SUBJECTS
DROP PROCEDURE IF EXISTS GetAllSubjectsProcessedData;

DROP PROCEDURE IF EXISTS InsertSubject;

DROP PROCEDURE IF EXISTS DeleteSubjectById;

DROP PROCEDURE IF EXISTS UpdateSubjectByID;

#WORKSHOPS
DROP PROCEDURE IF EXISTS GetAllWorkshops;

DROP PROCEDURE IF EXISTS GetWorkshopsByAvailable;

DROP PROCEDURE IF EXISTS GetWorkshopsByCurrentlySemester;

DROP PROCEDURE IF EXISTS InsertWorkshop;

DROP PROCEDURE IF EXISTS UpdateWorkshopAvailable;

DROP PROCEDURE IF EXISTS GetCompletedWorkshopsByStudent;

DROP PROCEDURE IF EXISTS GetAvailableWorkshopsNotEnrolledByStudent;

DROP PROCEDURE IF EXISTS GetEnrolledAvailableWorkshopsByStudent;

#REQUESTS

DROP PROCEDURE IF EXISTS GetAllRequestsProcessed;

DROP PROCEDURE IF EXISTS GetRequestByID;

DROP PROCEDURE IF EXISTS InsertRequest;

DROP PROCEDURE IF EXISTS GetRequestsByStudentRUT;

DROP PROCEDURE IF EXISTS GetRequestsByStudentRol;

DROP PROCEDURE IF EXISTS GetRequestsByDateRangeCreation;

DROP PROCEDURE IF EXISTS GetRequestsByCampus;

DROP PROCEDURE IF EXISTS GetRequestsByState;

DROP PROCEDURE IF EXISTS UpdateRequest;

DROP PROCEDURE IF EXISTS GetFilteredRequests;

#CONVALIDATIONS
DROP PROCEDURE IF EXISTS GetConvalidationsByRequestId;

DROP PROCEDURE IF EXISTS InsertConvalidation;

DROP PROCEDURE IF EXISTS UpdateConvalidation;

#WORKSHOPS_INSCRIPTIONS
DROP PROCEDURE IF EXISTS GetWorkshopsInscriptionsByWorkshopID;

DROP PROCEDURE IF EXISTS GetEnrolledAvailableWorkshopsByStudent;

DROP PROCEDURE IF EXISTS GetWorkshopsInscriptionsByWorkshopID;

DROP PROCEDURE IF EXISTS GetEnrolledAvailableWorkshopsByStudent;

#WORKSHOPS_GRADES
DROP PROCEDURE IF EXISTS GetWorkshopGradeByStudentID;

DROP PROCEDURE IF EXISTS GetWorkshopGradeByWorkshopID;

DROP PROCEDURE IF EXISTS InsertWorkshopGrade;